config/routes.rb
SampleApp::Application.routes.draw do
  resources :livevideos, only:[:create, :destroy]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'  
  

  

end

app/models/livevideo.rb
class Livevideo < ActiveRecord::Base
  validates :information, presence: true, length: { maximum: 20 }
  validates :location, presence: true
  validates :url, presence: true, uniqueness: true
  default_scope -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase}
  before_create :create_remember_token
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false}
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/models/video.rb
class Video < ActiveRecord::Base
  default_scope -> {order ('created_at DESC')}
  validates :videoinfo, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/livevideos_controller.rb
class LivevideosController < ApplicationController
  before_action :signed_in_user
  require 'open-uri' 
  
  def create
    @livevideo = Livevideo.new(livevideo_params)
    @livevideo.url =  "http://10.187.248.226:8080/#" + newpass(10)
    url = "http://api.map.baidu.com/geocoder/v2/?address=%s&output=json&ak=AA50c6765a5a346c22348295adca7877&city=上海市" % ("交大闵行校区" + @livevideo.location)
    url_escape = URI::escape(url) 
    content = open(url_escape).read 
    content_parsed = JSON.parse(content)
    @livevideo.lng =  content_parsed["result"]["location"]["lng"]
    @livevideo.lat =  content_parsed["result"]["location"]["lat"]
    @livevideos = Livevideo.all
    if @livevideo.save
      flash[:success] = "Live Video Created Successful!"      
      redirect_to current_user
    else
      redirect_to current_user
    end
  end

  def destroy
    Livevideo.find(params[:id]).destroy
    redirect_to current_user
  end

  private

    def livevideo_params
      params.require(:livevideo).permit(:information, :location, :url)
    end
    
    def newpass( len )
      chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
      newpass = ""
      1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
      return newpass
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @livevideo = Livevideo.new if signed_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def new
  end
 
  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
  
  def show
    @user = User.find(params[:id])
    @livevideo = Livevideo.new if signed_in?
    @livevideos = Livevideo.paginate(page: params[:page])
  end 
  
  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Mobile Eye!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    # Before filters

    def signed_in_user
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    @video = Video.new
  end

  def create
    if params[:information].present?
      @videos = 
      @videos.information = params[:information]      
    end
    redirect_to user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Mobile Eye"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/livevideos_helper.rb
module LivevideosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  def current_user?(user)
    user == current_user
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath if request.get?
  end
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 52 } )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://front.sjtu.edu.cn/">Mobile Eye</a>
    by 无线欢乐的小伙伴
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.sjtuhuaweiclub.com//">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Mobile Eye", root_path, id:"logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'logo.ico' %>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="flash alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>  
  </body>
</html>

app/views/livevideos/_livevideo.html.erb
<%= will_paginate @livevideos%>

<li>
  <span class="information">
    <%= link_to livevideo.information, livevideo.url %>
  </span>
  <span class="information"><%= livevideo.location %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(livevideo.created_at) %> ago.
  </span>
  <%= link_to "delete", livevideo, method: :delete, data: { confirm: "You sure?" }, title: livevideo.information %>
</li>

<%= will_paginate @livevideos%>

app/views/livevideos/new.html.erb
<h1>Livevideos#new</h1>
<p>Find me in app/views/livevideos/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_livevideo_form.html.erb
<%= form_for(@livevideo) do |f| %>
   <%= render 'shared/error_messages', object: f.object %> 
   <%= f.text_field :information, placeholder: "Description for Livevideo...", class: "description" %>
    <div class= "location"><%= f.select :location, [["第一餐饮大楼", "第一餐饮大楼"], ["第二餐饮大楼", "第二餐饮大楼"]], :prompt => "请选择地点" %></div>
  <%= f.submit "Create Live video", class: "btn btn-large btn-primary createsubmit" %>
<% end %>

app/views/shared/_map_canvas.html.erb
<script  type="text/javascript" src="http://api.map.baidu.com/api?v=1.5&ak=AA50c6765a5a346c22348295adca7877"></script>

<script type="text/javascript" >
   var bm_center = new BMap.Point(121.441588,31.03261)
   var map = new BMap.Map("map_canvas",{mapType: BMAP_HYBRID_MAP});
   map.centerAndZoom(bm_center, 16);
   map.addControl(new BMap.NavigationControl());
   map.addControl(new BMap.ScaleControl());
   map.addControl(new BMap.OverviewMapControl());
   map.addControl(new BMap.MapTypeControl());
   map.enableScrollWheelZoom();

   var locations =  <%= @livevideos.to_json.html_safe %>;
   var locNum = locations.length; 
   var marker = new Array(locNum); 
   var contentString ;
   for (i=0; i<locNum; ++i){ 
     marker[i] = new BMap.Marker(new BMap.Point(parseFloat(locations[i]["lng"]), parseFloat(locations[i]["lat"]))); 
     map.addOverlay(marker[i]);
     lan(marker[i],i);
     marker[i].setAnimation(BMAP_ANIMATION_BOUNCE); 
   }
   function lan(mypt,i){
     var ifonWin = new BMap.InfoWindow('<a href=' + locations[i]["url"] + '>' +  locations[i]["information"] + '</a>');
     mypt.addEventListener("click", function(){this.openInfoWindow(ifonWin);});
   }
</script>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(Livevideo.count, "livevideo") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
  <div class="center hero-unit">
    <h1>Welcome to the MOBILE EYE </h1>

    <h2>
      This is the home page for the first
      <a href="http://www.sjtuhuaweiclub.com/">SJTU HuaWei</a>
      app challenge.
    </h2>
    <%= image_tag("logo1.png", alt: "mobile eye logo") %>
   <h3 style=" font-size: 1px;"><%= link_to "Sign in now!", signin_path, class: "btn btn-big btn-flat", disabled: true %> </h3> <p  style=" font-size: 5px;">New user? <%= link_to "Sign up now!", signup_path %></p> 
  </div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<table width="100%">
<tr>
<td colspan="1" >
<div >
  <%= gravatar_for @user %>
  <%= @user.name %>
</div>
</td>
<td colspan="4" align="right">
<div class="createvideo"><%= render 'shared/livevideo_form' %></div>
</td>
</tr>
</table>
<table width="100%">
<tr>
<td colspan="4">
<div id="map_canvas"><%= render 'shared/map_canvas' %></div>
</td>

<td colspan = "1">
<div class="list">
  <% if Livevideo.any? %>
    <h3>Live Videos (<%= Livevideo.count %>)</h3>
    <ol class="livevideos">
      <%= render @livevideos %>
    </ol>
    <%= will_paginate @livevideos %>
  <% end %>
</div>

</td>
</tr>
</table>

app/views/videos/_video.html.erb
<li>
  <span class="description"><%= video.information %></span>,
  <span class="description"><%= video.location %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(video.created_at) %> ago.
  </span>
</li>

app/views/videos/_videos.html.erb
<li>
  <span class="content"><%= video.videoinfo %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(video.created_at) %> ago.
  </span>
</li>